<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.whim</groupId>
        <artifactId>whim</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>whim-start</artifactId>

    <dependencies>
        <!-- whim-web -->
        <dependency>
            <groupId>com.whim</groupId>
            <artifactId>whim-web</artifactId>
        </dependency>
        <!-- Sa-Token 认证模块 -->
        <dependency>
            <groupId>com.whim</groupId>
            <artifactId>whim-satoken</artifactId>
        </dependency>
        <!-- 系统业务模块 -->
        <dependency>
            <groupId>com.whim</groupId>
            <artifactId>whim-system</artifactId>
        </dependency>
        <!-- Flyway 数据库版本迁移 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-flyway</artifactId>
        </dependency>
        <!-- Flyway MySQL 数据库支持 -->
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-mysql</artifactId>
            <scope>runtime</scope>
        </dependency>
        <!-- webmvc-test -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
