server:
  port: 8080
spring:
  application:
    name: whim
  # 开发环境
  profiles:
    active: @profiles_active@
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true
