/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NEl: typeof import('naive-ui')['NEl']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NFlex: typeof import('naive-ui')['NFlex']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NH2: typeof import('naive-ui')['NH2']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NResult: typeof import('naive-ui')['NResult']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpace: typeof import('naive-ui')['NSpace']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
  const NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
  const NButton: typeof import('naive-ui')['NButton']
  const NCard: typeof import('naive-ui')['NCard']
  const NConfigProvider: typeof import('naive-ui')['NConfigProvider']
  const NDialogProvider: typeof import('naive-ui')['NDialogProvider']
  const NDivider: typeof import('naive-ui')['NDivider']
  const NDrawer: typeof import('naive-ui')['NDrawer']
  const NDrawerContent: typeof import('naive-ui')['NDrawerContent']
  const NEl: typeof import('naive-ui')['NEl']
  const NEmpty: typeof import('naive-ui')['NEmpty']
  const NFlex: typeof import('naive-ui')['NFlex']
  const NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
  const NH2: typeof import('naive-ui')['NH2']
  const NIcon: typeof import('naive-ui')['NIcon']
  const NLayout: typeof import('naive-ui')['NLayout']
  const NLayoutContent: typeof import('naive-ui')['NLayoutContent']
  const NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
  const NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
  const NLayoutSider: typeof import('naive-ui')['NLayoutSider']
  const NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
  const NMenu: typeof import('naive-ui')['NMenu']
  const NMessageProvider: typeof import('naive-ui')['NMessageProvider']
  const NModalProvider: typeof import('naive-ui')['NModalProvider']
  const NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
  const NResult: typeof import('naive-ui')['NResult']
  const NScrollbar: typeof import('naive-ui')['NScrollbar']
  const NSpace: typeof import('naive-ui')['NSpace']
  const NTag: typeof import('naive-ui')['NTag']
  const NText: typeof import('naive-ui')['NText']
  const NTooltip: typeof import('naive-ui')['NTooltip']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}